services:
  db:
    image: postgres:16-alpine
    pull_policy: always
    environment:
      POSTGRES_DB: reservasdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres -d reservasdb
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    image: agussesin/reservas-backend:v0.1.0
    pull_policy: always
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=reservasdb;Username=postgres;Password=${DB_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: agussesin/reservas-frontend:v0.1.0
    pull_policy: always
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_started

volumes:
  db_data:
